/* This file was generated by r.out.leaflet GRASS GIS module. */

var layerInfos = [
   {title: "Flooding_0.0", file: "Flooding_0.0.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
,   {title: "RealisticFlood_0.3", file: "RealisticFlood_0.3.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
,   {title: "RealisticFlood_0.6", file: "RealisticFlood_0.6.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
,   {title: "RealisticFlood_0.8999999999999999", file: "RealisticFlood_0.8999999999999999.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
,   {title: "RealisticFlood_1.2", file: "RealisticFlood_1.2.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
,   {title: "RealisticFlood_1.5", file: "RealisticFlood_1.5.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
,   {title: "RealisticFlood_1.8", file: "RealisticFlood_1.8.png", bounds: [[44.80868193, -110.05984318], [44.94111152, -110.21534749]], opacity: 1.0}
];
